name: Knuckles Review Sample

on:
  pull_request_review:
    types: [submitted]

jobs:
  knuckles_review:
    runs-on: ubuntu-latest

    steps:
      - name: Knuckles Review
        if: ${{ github.event.review.state == 'approved' }}
        uses: ArthurLobopro/knuckles-review@v0.3
        with:
          type: "Approved"
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Knuckles Review
        if: ${{ github.event.review.state == 'changes_requested' }}
        uses: ArthurLobopro/knuckles-review@v0.3
        with:
          type: "IDK"
        env:
          GITHUB_TOKEN: ${{ github.token }}
    
